import React from 'react'
import { getPayload } from 'payload'
import configPromise from '@/payload.config'
import { OpportunityCard } from '@/components/cards/OpportunityCard'
import { Navbar } from '@/components/layout/Navbar'
import { Hero } from '@/components/home/Hero'
// Import the types generated by Payload
import { Opportunity, Partner } from '@/payload-types'

export default async function HomePage() {
  const payload = await getPayload({ config: configPromise })

  // Explicitly typing the collection ensures 'docs' has the right properties
  const { docs: opportunities } = await payload.find({
    collection: 'opportunities',
    depth: 1, // This fetches the Partner object instead of just an ID
    sort: '-createdAt',
  })

  return (
    <div className="min-h-screen bg-white">
      <Navbar />
      <Hero />
      
      <section className="max-w-7xl mx-auto px-4 py-16">
        <div className="flex flex-col lg:flex-row gap-12">
          {/* Sidebar ... */}
          <div className="flex-1">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {opportunities.map((opp: Opportunity) => {
                // Since depth is 1, organization is a Partner object
                const org = opp.organization as Partner;
                
                return (
                  <OpportunityCard
                    key={opp.id}
                    title={opp.title}
                    organizationName={org?.name || 'Partner Org'}
                    category={opp.category}
                    documentation={opp.documentation}
                    deadline={opp.deadline}
                    isVerified={opp.isVerified || false}
                    applyLink={opp.applyLink}
                  />
                )
              })}
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}