release: python manage.py migrate --no-input
web: gunicorn config.wsgi:application --workers 2 --worker-class gthread --worker-connections 1000 --max-requests 1000 --max-requests-jitter 50 --timeout 120 --bind 0.0.0.0:$PORT --access-logfile - --error-logfile -
