# Generated by Django 5.2.10 on 2026-02-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(choices=[('apply', 'Apply Button'), ('view_brochure', 'View Brochure'), ('compose_email', 'Compose Email'), ('view_details', 'View Details')], default='apply', max_length=50)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_clicked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Click Analytics',
                'verbose_name_plural': 'Click Analytics',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The opportunity title - be clear and descriptive', max_length=255)),
                ('organization_name', models.CharField(help_text='The organization offering this opportunity', max_length=255)),
                ('location', models.CharField(blank=True, choices=[('kenya', 'Kenya'), ('uganda', 'Uganda'), ('tanzania', 'Tanzania'), ('rwanda', 'Rwanda'), ('remote', 'Remote'), ('multiple', 'Multiple Locations')], help_text='Where is this opportunity located?', max_length=50, null=True)),
                ('category', models.CharField(choices=[('job', 'Job'), ('scholarship', 'Scholarship'), ('internship', 'Internship'), ('fellowship', 'Fellowship'), ('training', 'Training')], default='job', help_text='The type of opportunity', max_length=50)),
                ('required_documents', models.JSONField(blank=True, default=list, help_text='Which IDs are accepted for this opportunity? (Powers the Advanced Filters)')),
                ('application_type', models.CharField(choices=[('link', 'External Link'), ('email', 'Email Application'), ('pdf', 'PDF Brochure')], default='link', help_text='How should applicants apply?', max_length=20)),
                ('external_url', models.URLField(blank=True, help_text="URL to MS Forms/Website (for 'External Link' type)", null=True)),
                ('application_email', models.EmailField(blank=True, help_text="Email address for applications (for 'Email' type)", max_length=254, null=True)),
                ('email_subject_line', models.CharField(blank=True, help_text='Suggested subject line for email applications', max_length=255, null=True)),
                ('brochure_upload', models.FileField(blank=True, help_text='PDF brochure for ads (e.g., Akili Dada Office Manager)', null=True, upload_to='brochures/')),
                ('prep_checklist', models.JSONField(blank=True, default=list, help_text="List items like 'Resume', 'Cover Letter', 'Recommendation Letters'")),
                ('is_verified', models.BooleanField(default=False, help_text="Shows 'WhatsApp Group Verified' badge")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this opportunity is currently visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('deadline', models.DateTimeField(blank=True, help_text='Application deadline', null=True)),
                ('raw_data', models.TextField(blank=True, help_text='Raw text pasted from WhatsApp (for admin convenience)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
