# Generated by Django 5.2.11 on 2026-02-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='email_subject_line',
            field=models.CharField(blank=True, default='', help_text='Suggested subject line for email applications', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, choices=[('kenya', 'Kenya'), ('uganda', 'Uganda'), ('tanzania', 'Tanzania'), ('rwanda', 'Rwanda'), ('remote', 'Remote'), ('multiple', 'Multiple Locations')], default='', help_text='Where is this opportunity located?', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='raw_data',
            field=models.TextField(blank=True, default='', help_text='Raw text pasted from WhatsApp (for admin convenience)'),
            preserve_default=False,
        ),
    ]
