# Generated by Django 5.2.10 on 2026-02-06 21:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_job_email_subject_line_alter_job_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Subscriber email address', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Whether the subscription is confirmed and active')),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, help_text='Token for email confirmation', unique=True)),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='Last time this subscriber was notified of new opportunities', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the subscription was confirmed', null=True)),
            ],
            options={
                'verbose_name': 'Email Subscription',
                'verbose_name_plural': 'Email Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, help_text='City where the opportunity is located', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='commitment',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('short_term', 'Short-term'), ('long_term', 'Long-term')], help_text='Full-time, part-time, short-term, or long-term', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('any', 'Any Level')], help_text='Required education level', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='funding_type',
            field=models.CharField(blank=True, choices=[('fully', 'Fully Funded'), ('partially', 'Partially Funded'), ('none', 'Not Funded')], help_text='Funding status of this opportunity', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Is this a paid opportunity?'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_rolling',
            field=models.BooleanField(default=False, help_text='Is this a rolling deadline opportunity?'),
        ),
        migrations.AddField(
            model_name='job',
            name='stipend_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum stipend amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stipend_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum stipend amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='target_group',
            field=models.CharField(blank=True, choices=[('refugees', 'Refugees'), ('youth', 'Youth'), ('women', 'Women'), ('all', 'All')], help_text='Target audience for this opportunity', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], help_text='Remote, hybrid, or on-site', max_length=20),
        ),
    ]
