# Generated by Django 5.2.10 on 2026-02-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_subscription_job_city_job_commitment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the opportunity'),
        ),
    ]
