# Generated by Django on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Partner organization name', max_length=255, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='Logo image URL', null=True)),
                ('website_url', models.URLField(blank=True, help_text='Partner website URL', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight partner on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['name'],
            },
        ),
    ]
