# Generated by Django 5.2.10 on 2026-02-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='org_logo',
            field=models.ImageField(blank=True, help_text='Organization logo for branding', null=True, upload_to='logos/%Y/%m/'),
        ),
    ]
