# Generated by Django 5.2.10 on 2026-02-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_partner'),
    ]

    # This migration duplicated the field addition already present in
    # 0008_job_org_logo from a parallel branch.
    operations = []
