# Generated by Django 5.2.10 on 2026-02-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_add_org_logo'),
        ('listings', '0008_job_org_logo'),
    ]

    operations = [
    ]
