# Generated by Django 5.2.10 on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_merge_0008_add_org_logo_0008_job_org_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload partner logo image from your computer', null=True, upload_to='partners/logos/%Y/%m/'),
        ),
    ]

