# Generated by Django 5.2.10 on 2026-03-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_partner_logo_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('partner', models.CharField(blank=True, help_text='Partner organization hosting or amplifying the event', max_length=255)),
                ('category', models.CharField(choices=[('tech', 'Tech & Innovation'), ('policy', 'Policy & Governance'), ('community', 'Community Action'), ('climate', 'Climate & Sustainability')], default='community', help_text='What field or theme does this event line up with?', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Event description and storyline')),
                ('requirements', models.TextField(blank=True, help_text='Requirements to attend (documents, registration)')),
                ('location', models.CharField(blank=True, help_text='Physical location or online platform', max_length=255)),
                ('directions', models.TextField(blank=True, help_text='Directions or entrance notes for the venue')),
                ('start_time', models.DateTimeField(help_text='When the event starts')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the event ends (optional)', null=True)),
                ('is_virtual', models.BooleanField(default=False, help_text='Is this event fully virtual?')),
                ('stream_url', models.URLField(blank=True, help_text='Livestream link when virtual')),
                ('is_active', models.BooleanField(default=True, help_text='Hide events that have passed or are canceled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_time'],
            },
        ),
    ]
