# Generated by Django 5.2.10 on 2026-02-12 23:25

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_partner_logo_upload'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedUpUser',
            fields=[
            ],
            options={
                'verbose_name': 'Signed Up User',
                'verbose_name_plural': 'Signed Up Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UpdateSubscriber',
            fields=[
            ],
            options={
                'verbose_name': 'Update Subscriber',
                'verbose_name_plural': 'Update Subscribers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('listings.subscription',),
        ),
    ]
